const constants = {
    ADD_NEW_EMPLOYEE: "ADD_NEW_EMPLOYEE",
	CHANGE_EMPLOYEE_VALUE: "CHANGE_EMPLOYEE_VALUE",
	SET_EMPLOYEE: "SET_EMPLOYEE",
	CHANGE_EDIT_EMPLOYEE: "CHANGE_EDIT_EMPLOYEE",
	CHANGE_NEW_EMPLOYEE: "CHANGE_NEW_EMPLOYEE",
	CHANGE_OPEN_DIALOG_VALUE: "CHANGE_OPEN_DIALOG_VALUE",
	CHANGE_STATE_VALUE: "CHANGE_STATE_VALUE",
	FILTERING: "FILTERING"
}

export default constants