const constants = {
	CHANGE_EMPLOYEE_VALUE: "CHANGE_EMPLOYEE_VALUE",
	SET_EMPLOYEE: "SET_EMPLOYEE",
	CHANGE_EDIT_EMPLOYEE: "CHANGE_EDIT_EMPLOYEE",
	REMOVE_DAY: "REMOVE_DAY",
	SET_GOAL: "SET_GOAL",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
	FETCH_RESORT_NAMES: "FETCH_RESORT_NAMES",
	CANCEL_FETCHING: "CANCEL_FETCHING",
	CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
	CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS"
}

export default constants