const constants = {
	CHANGE_EMPLOYEE_VALUE: "CHANGE_EMPLOYEE_VALUE",
	SET_EMPLOYEE: "SET_EMPLOYEE",
	CHANGE_EDIT_EMPLOYEE: "CHANGE_EDIT_EMPLOYEE",
	CHANGE_STATE_VALUE: "CHANGE_STATE_VALUE"
}

export default constants